version: 0.1

environment_variables:
  plaintext:
    ENV_KEY: 'environment-value'
    PLATFORM: 'shoes'

phases:
  install:
    commands:
      - 'echo "Here I would be installing extra software for $PLATFORM"'
  pre_build:
    commands:
      - 'echo "Here I would be setting up for the build, like using $ENV_KEY to check out other repos"'
      - 'echo "More build setup, maybe inject build id $CODEBUILD_BUILD_ID"'
  build:
    commands:
      - 'echo "Here I would compile stuff if needed"'
      - 'echo "Run some tests"'
      - 'python -m unittest discover'
  post_build:
    commands:
      - 'echo "Here I package stuff for distribution"'
      - 'mkdir -p dist'
      - 'which tar'
      - 'which gzip'
      - 'tar -cvf dist/thing.zip dictionary.txt findwords'

artifacts:
  files:
    - 'dist/*'
  discard-paths: true
