version: 0.1

environment_variables:
  plaintext:
    ENV_KEY: 'environment-value'
    PLATFORM: 'shoes'

phases:
  install:
    # Install additional SW not included in the docker image
    commands:
      - 'echo "Here I prepare my platform"'
      - 'apt-get -y install zip'
  pre_build:
    # Prepare for executing the build. Maybe point to your artifactory, npm install, checkout more repos, etc.
    commands:
      - 'echo "Here I prepare my environment"'
      - 'pip install pytest'
      - 'echo ${CODEBUILD_BUILD_ID} > manifest.txt'
  build:
    # Compile, test, bundle, whatever produces deployable artifacts
    commands:
      - 'echo "Here I build and test things"'
      - 'python -m unittest discover'
  post_build:
    # package up your deployables, generate deploy scripts, etc.
    commands:
      - 'echo "Here I package stuff for distribution"'
      - 'mkdir -p dist'
      - 'zip -r dist/thing.zip dictionary.txt manifest.txt findwords -x \*.pyc'

artifacts:
  files:
    - 'dist/*'
  discard-paths: true
