---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'CodeBuild Demonstration Template'

Resources:
  BasicVoggleBuild:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      # See http://docs.aws.amazon.com/codebuild/latest/userguide/create-project.html#create-project-cli
      Name: 'BasicVoggleBuild'
      Description: 'Basic CodeBuild definition for Voggle'
      ServiceRole: !Ref BasicVoggleBuildRole
      Source:
        Type: GITHUB
        Location: 'https://github.com/mccormickmichael/voggle.git'
        # BuildSpec: inline or implicit buildspec.yml
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        # These override variables defined in buildspec.yml (intended to be per-build values)
        EnvironmentVariables: []
        # AWS-managed docker image. Can use your own stored in AWS ECR
        Image: 'aws/codebuild/eb-python-2.7-amazonlinux-64:2.1.6'
        # Required, only legal value
        Type: LINUX_CONTAINER
      Artifacts:
        Type: S3
        Location: !ImportValue ThousandleavesArtifactBucket
        # the next three properties determine where artifacts are placed in the bucket. Only valid for S3 type.
        # ${Path}/${NamespaceType}/${Name}
        Path: voggle
        # Either BUILD_ID or NONE
        NamespaceType: BUILD_ID
        # Post-fix path. Directory if Packaging is NONE, zip file name if Packaging is ZIP
        Name: results
        # S3 only. ZIP or NONE
        Packaging: NONE
      TimeoutInMinutes: 10
      Tags: []
  BasicVoggleBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument: >
        {"Version":"2012-10-17","Statement":{"Effect":"Allow","Principal":{"Service":"codebuild.amazonaws.com"},"Action":"sts:AssumeRole"}}
      ManagedPolicyArns:
        # These could(should?) be custom policies
        - 'arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchLogsFullAccess'
        - !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':policy/machine-deploy-s3' ] ]

        
